version: '1.0'
stages:
- build
- push
steps:
  build:
    title: Building Docker Image
    type: build
    stage: build
    image_name: spark-operator-py
    working_directory: {{CLONE_STEP_NAME}}
    tag: 'master'
    dockerfile: Dockerfile
  push_to_dockerhu:
    stage: 'push'
    type: push
    title: Pushing to a registry
    candidate: ${{build}}
    tag: 'latest'
    registry: dockerhub
    image_name: koolay/spark-operator-py    
